# Атрибут 'version' убран, как и просил docker-compose v2
services:
  app:
    build: .
    container_name: jewelry-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    # Просто подключаемся к уже существующей внешней сети
    networks:
      - jewelry-app-network

networks:
  jewelry-app-network:
    external: true