import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';

const HomepageConfig = sequelize.define('HomepageConfig', {
    text1_title:   { type: DataTypes.STRING, allowNull: true },
    text1_content: { type: DataTypes.TEXT, allowNull: true },
    image1_url: { type: DataTypes.STRING, allowNull: true },
    image1_alt: { type: DataTypes.STRING, allowNull: true },
    image2_url: { type: DataTypes.STRING, allowNull: true },
    image2_alt: { type: DataTypes.STRING, allowNull: true },
    image3_url: { type: DataTypes.STRING, allowNull: true },
    image3_alt: { type: DataTypes.STRING, allowNull: true },
    image4_url: { type: DataTypes.STRING, allowNull: true },
    image4_alt: { type: DataTypes.STRING, allowNull: true },
    image5_url: { type: DataTypes.STRING, allowNull: true },
    image5_alt: { type: DataTypes.STRING, allowNull: true },
    image6_url: { type: DataTypes.STRING, allowNull: true },
    image6_alt: { type: DataTypes.STRING, allowNull: true },
    text2_title:   { type: DataTypes.STRING, allowNull: true },
    text2_content: { type: DataTypes.TEXT, allowNull: true },
    image7_url: { type: DataTypes.STRING, allowNull: true },
    image7_alt: { type: DataTypes.STRING, allowNull: true },
    image8_url: { type: DataTypes.STRING, allowNull: true },
    image8_alt: { type: DataTypes.STRING, allowNull: true },
    image9_url: { type: DataTypes.STRING, allowNull: true },
    image9_alt: { type: DataTypes.STRING, allowNull: true },
    image10_url: { type: DataTypes.STRING, allowNull: true },
    image10_alt: { type: DataTypes.STRING, allowNull: true },
    text3_title:   { type: DataTypes.STRING, allowNull: true },
    text3_content: { type: DataTypes.TEXT, allowNull: true },
    image11_url: { type: DataTypes.STRING, allowNull: true },
    image11_alt: { type: DataTypes.STRING, allowNull: true },
    image12_url: { type: DataTypes.STRING, allowNull: true },
    image12_alt: { type: DataTypes.STRING, allowNull: true },
    image13_url: { type: DataTypes.STRING, allowNull: true },
    image13_alt: { type: DataTypes.STRING, allowNull: true },
    image14_url: { type: DataTypes.STRING, allowNull: true },
    image14_alt: { type: DataTypes.STRING, allowNull: true },
    text4_title:   { type: DataTypes.STRING, allowNull: true },
    text4_content: { type: DataTypes.TEXT, allowNull: true },
    image15_url: { type: DataTypes.STRING, allowNull: true },
    image15_alt: { type: DataTypes.STRING, allowNull: true },
    image16_url: { type: DataTypes.STRING, allowNull: true },
    image16_alt: { type: DataTypes.STRING, allowNull: true },
    image17_url: { type: DataTypes.STRING, allowNull: true },
    image17_alt: { type: DataTypes.STRING, allowNull: true },
    text5_title:   { type: DataTypes.STRING, allowNull: true },
    text5_content: { type: DataTypes.TEXT, allowNull: true },
    image18_url: { type: DataTypes.STRING, allowNull: true },
    image18_alt: { type: DataTypes.STRING, allowNull: true },
    image19_url: { type: DataTypes.STRING, allowNull: true },
    image19_alt: { type: DataTypes.STRING, allowNull: true },
    image20_url: { type: DataTypes.STRING, allowNull: true },
    image20_alt: { type: DataTypes.STRING, allowNull: true },
    image21_url: { type: DataTypes.STRING, allowNull: true },
    image21_alt: { type: DataTypes.STRING, allowNull: true },
}, {
    timestamps: true,
    tableName: 'homepage_config'
});

export default HomepageConfig;